<?php
   $sensors = array("none", "Heating Up", "Heating Down", "Solar Up", "Solar Down", "Solar Boiler", "Outside north side", "Warm Water Pipe", "Warm Water Heating", "temp3", "temp4", "temp5", "temp6", "temp7", "temp8", "temp9", "temp10", "temp11");
   $colors = array("black", "slateblue", "red", "orange", "BlueViolet", "green", "blue", "gold", "grey", "yellowGreen", "purple", "salmon", "chartreuse");
?>

