<?php
   $sensors = array("none", "Collector Fluid", "Hot Water Output", "Solar Storage High", "External Heating System", "Outside temperature", "Solar Storage Low", "temp1", "temp2", "temp3", "temp4", "temp5", "temp6", "temp7", "temp8", "temp9", "temp10", "temp11");
   $colors = array("black", "slateblue", "red", "orange", "BlueViolet", "green", "blue", "gold", "grey", "yellowGreen", "purple", "salmon", "chartreuse");
?>

